name: tool_calling_playground
description: A sample command-line application.
version: 1.0.0
publish_to: none
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  llm_tool_calling: ^0.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.32.0
  build_runner: ^2.16.0
  llm_tool_calling_generator: ^0.3.0
